# Generated by Django 4.0.3 on 2022-03-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_rename_locate_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='galore',
            name='location',
            field=models.ManyToManyField(to='pictures.location'),
        ),
    ]
