# Generated by Django 4.0.3 on 2022-03-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_remove_galore_image_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='galore',
            name='image_pic',
            field=models.ImageField(default='', upload_to='photos/'),
        ),
    ]
