# Generated by Django 4.0.3 on 2022-03-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0013_alter_galore_image_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galore',
            old_name='image_pic',
            new_name='image',
        ),
    ]
