# Generated by Django 4.0.3 on 2022-03-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0014_rename_image_pic_galore_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='galore',
            name='category',
            field=models.ManyToManyField(to='pictures.category'),
        ),
    ]
