# Generated by Django 4.0.3 on 2022-03-28 19:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0015_category_galore_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galore',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
